let arr = ["Apple", "Banana", "Mango"];
let result = arr.join();
console.log(result); 
let result1 = arr.join(" - ");
console.log(result1); 
let result2 = arr.join(""); 
console.log(result2);
let arr1 = [1, "Hello", undefined, null, true];
let result3 = arr1.join(", ");
console.log(result3); 
