version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app                   # Mount source code for hot reload
      - /app/node_modules        # Avoid local node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload in Docker
